// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamPriceBot.Infrastructure.Persistence;

#nullable disable

namespace SteamPriceBot.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SteamPriceBot.Domain.Entities.MarketItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MarketItems");
                });

            modelBuilder.Entity("SteamPriceBot.Domain.Entities.PriceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MarketItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrackedItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketItemId");

                    b.ToTable("PriceRecords");
                });

            modelBuilder.Entity("SteamPriceBot.Domain.Entities.TrackedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MarketItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketItemId");

                    b.ToTable("TrackedItems");
                });

            modelBuilder.Entity("SteamPriceBot.Domain.Entities.MarketItem", b =>
                {
                    b.OwnsOne("SteamPriceBot.Domain.ValueObjects.ItemId", "ItemId", b1 =>
                        {
                            b1.Property<Guid>("MarketItemId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("AppId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("AppId");

                            b1.Property<string>("MarketHashName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("MarketHashName");

                            b1.HasKey("MarketItemId");

                            b1.ToTable("MarketItems");

                            b1.WithOwner()
                                .HasForeignKey("MarketItemId");
                        });

                    b.Navigation("ItemId");
                });

            modelBuilder.Entity("SteamPriceBot.Domain.Entities.PriceRecord", b =>
                {
                    b.HasOne("SteamPriceBot.Domain.Entities.MarketItem", null)
                        .WithMany("PriceHistory")
                        .HasForeignKey("MarketItemId");

                    b.OwnsOne("SteamPriceBot.Domain.ValueObjects.PriceValue", "Price", b1 =>
                        {
                            b1.Property<Guid>("PriceRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount");

                            b1.HasKey("PriceRecordId");

                            b1.ToTable("PriceRecords");

                            b1.WithOwner()
                                .HasForeignKey("PriceRecordId");

                            b1.OwnsOne("SteamPriceBot.Domain.ValueObjects.Currency", "Currency", b2 =>
                                {
                                    b2.Property<Guid>("PriceValuePriceRecordId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CurrencyCode");

                                    b2.HasKey("PriceValuePriceRecordId");

                                    b2.ToTable("PriceRecords");

                                    b2.WithOwner()
                                        .HasForeignKey("PriceValuePriceRecordId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("SteamPriceBot.Domain.Entities.TrackedItem", b =>
                {
                    b.HasOne("SteamPriceBot.Domain.Entities.MarketItem", "Item")
                        .WithMany()
                        .HasForeignKey("MarketItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("SteamPriceBot.Domain.ValueObjects.AlertThreshold", "Threshold", b1 =>
                        {
                            b1.Property<Guid>("TrackedItemId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("ThresholdAmount");

                            b1.HasKey("TrackedItemId");

                            b1.ToTable("TrackedItems");

                            b1.WithOwner()
                                .HasForeignKey("TrackedItemId");
                        });

                    b.Navigation("Item");

                    b.Navigation("Threshold");
                });

            modelBuilder.Entity("SteamPriceBot.Domain.Entities.MarketItem", b =>
                {
                    b.Navigation("PriceHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
